### ISSUE TITLE
Select and use platform installed fonts

### ISSUE THREAD

**Issue by cecilios** [lenmus/lomse#102]
A solution for using platform installed fonts is required.

Currently, Lomse only uses the fonts distributed with liblomse package. This causes different problems:

- No proper text rendering when the score is using languages not supported in current fonts used by lomse (i.e. Japanese or Korean).

- In MusicXML files the font-name style attribute recommends fonts by name. Lomse should be able to select the most suitable font from installed fonts.

- Explicit font name information is not enough. In many cases there are different font files for each font name: i.e. one for normal font, another for bold and a third one for italic.

- As Lomse is platform independent, the solution must not force to add if preprocessor directives to select the platform and to add platform dependent code. But in any case, platform dependent code is needed. To solve this, some ideas:
    - Transfer the responsibility to the user application, that will inform lomse about font paths.
    - As the code for previous solution will be common to all applications in a given platform, this code could be packaged in platform dependent lomse modules for dealing with fonts. I will code only the module for Linux. The modules for all other platforms will have to be coded by contributors.
    - Enable both solutions. When there is no lomse fonts module for a platform, the user could simply inform lomse about fonts paths.

**Comment by juuk100** [comment]
It is a very good idea.

With this issue I am currently using a little modification to lomse.
I have modified it to load the fonts I want to use.

m_lomse.set_default_fonts_path (myRSCFolder);
m_lomse.set_text_font_name ("myfont");

This calls up the following fonts in the Resources folder:
myfont-BoldItalic.ttf
myfont-Bold.ttf
myfont-Italic.ttf
myfont-Regular.ttf

Unfortunately, MusixXML does not work with bold or Italic effects (I may have misunderstood xml).

However, since I can print the font I want, it does not matter.

**Comment by cecilios** [comment]
@juuk100 
MusicXML does support bold and italics. See http://www.musicxml.com/for-developers/musicxml-dtd/common-elements/

```
<!--
    The font entity gathers together attributes for
    determining the font within a directive or direction.
    They are based on the text styles for Cascading
    Style Sheets. The font-family is a comma-separated list
    of font names. These can be specific font styles such
    as Maestro or Opus, or one of several generic font styles:
    music, engraved, handwritten, text, serif, sans-serif,
    handwritten, cursive, fantasy, and monospace. The music,
    engraved, and handwritten values refer to music fonts;
    the rest refer to text fonts. The fantasy style refers to
    decorative text such as found in older German-style
    printing. The font-style can be normal or italic. The
    font-size can be one of the CSS sizes (xx-small, x-small,
    small, medium, large, x-large, xx-large) or a numeric
    point size. The font-weight can be normal or bold. The
    default is application-dependent, but is a text font vs.
    a music font.
-->
<!ENTITY % font
    "font-family  CDATA  #IMPLIED
     font-style   CDATA  #IMPLIED
     font-size    CDATA  #IMPLIED
     font-weight  CDATA  #IMPLIED">
```


Current partial bypass for this problem is what you are probably using:

- Invoke one time m_lomse.set_default_fonts_path() to specify the path to use.
- When lomse does not find a font, it will the generate a Request for the font file name. Yoour application will have to hadle this request and provide a font file name. An example:

```
void MyApp::initialize_lomse()
{
    ...

    //Now, initialize the library with these values
    m_lomse.init_library(pixel_format, resolution, reverse_y_axis, m_lomseReporter);

    //set callbacks
    m_lomse.set_notify_callback(this, lomse_event_handler_method);
    m_lomse.set_request_callback(this, lomse_request_handler_method);
}

void MyApp::on_lomse_request(Request* pRequest)
{
    int type = pRequest->get_request_type();
    switch (type)
    {
        case k_dynamic_content_request:
            generate_dynamic_content( dynamic_cast<RequestDynamic*>(pRequest) );
            break;

        case k_get_font_filename:
            get_font_filename( dynamic_cast<RequestFont*>(pRequest) );
            break;

        default:
            LOMSE_LOG_ERROR(str(boost::format("Unknown request %d") % type));
    }
}

void MyApp::get_font_filename(RequestFont* pRequest)
{
    //This is just a trivial example. In real applications you should
    //use operating system services to find a suitable font

    //notes on parameters received:
    // - fontname can be either the face name (i.e. "Book Antiqua") or
    //   the familly name (i.e. "Liberation sans")

    const string& fontname = pRequest->get_fontname();
    bool bold = pRequest->get_bold();
    bool italic = pRequest->get_italic();

    string path = "/usr/share/fonts/truetype/";

    //if family name, choose a font name
    string name = fontname;
    if (name == "serif")
        name = "Times New Roman";
    else if (name == "sans-serif")
        name = "Tahoma";
    else if (name == "handwritten" || name == "cursive")
        name = "Monotype Corsiva";
    else if (name == "monospaced")
        name = "Courier New";

    //choose a suitable font file
    string fontfile;
    if (name == "Times New Roman")
    {
        if (italic && bold)
            fontfile = "freefont/FreeSerifBoldItalic.ttf";
        else if (italic)
            fontfile = "freefont/FreeSerifItalic.ttf";
        else if (bold)
            fontfile = "freefont/FreeSerifBold.ttf";
        else
            fontfile = "freefont/FreeSerif.ttf";
    }

    else if (name == "Tahoma")
    {
        if (bold)
            fontfile = "freefont/FreeSansOblique.ttf";
        else
            fontfile = "freefont/FreeSans.ttf";
    }

    else if (name == "Monotype Corsiva")
    {
        fontfile = "ttf-dejavu/DejaVuSans-Oblique.ttf";
    }

    else if (name == "Courier New")
    {
        if (italic && bold)
            fontfile = "freefont/FreeMonoBoldOblique.ttf";
        else if (italic)
            fontfile = "freefont/FreeMonoOblique.ttf";
        else if (bold)
            fontfile = "freefont/FreeMonoBold.ttf";
        else
            fontfile = "freefont/FreeMono.ttf";
    }

    else
        fontfile = "freefont/FreeSerif.ttf";


    pRequest->set_font_fullname( path + fontfile );
}
```
