### ISSUE TITLE
How do I specify the notation area?

### ISSUE THREAD

**Issue by juuk100** [lenmus/lomse#113]
I want to change the notation display area in the same MusicXML file as the attached image.
Mobile device users will need to show a little measure on a line because the screen is too small.
You can automatically display the measures on the score to fit the area size, or you can enter the number of measures to display manually.
This should not display the score on a page-by-page basis.
(If the score is long)
It should be displayed vertically without any gaps.

![2018-01-10 10 04 00](https://user-images.githubusercontent.com/15763813/34751917-8db52296-f5f2-11e7-95a5-3514040f0431.png)
![2018-01-10 10 03 35](https://user-images.githubusercontent.com/15763813/34751927-9c054e8e-f5f2-11e7-86e4-7829b9be6c48.png)

**Comment by cecilios** [comment]
Your question has three aspects:

### 1.  Automatically adjust the number of measures to fit the area size

This is related to the 'fluidity' concept: how the content adapts to window dimensions. Lomse currently does not include a 'free-flow' layout algorithm. Current layout algorithm is designed for laying out the document on a fixed page width on a page-by-page basis. Therefore, the only way of changing the width is by changing the document page size. But this is not difficult:

```
if (SpInteractor spInteractor = m_pPresenter->get_interactor(0).lock())
{
    Document* pDoc = m_pPresenter->get_document_raw_ptr();
    ImoPageInfo* pPageInfo = pDoc->get_page_info();
    pPageInfo->set_page_size(USize uPageSize)
	or	
    pPageInfo->set_page_width(LUnits value)
	or
    pPageInfo->set_page_height(LUnits value)
```

You can also remove the margins:
```
pPageInfo->set_top_margin(0);
pPageInfo->set_left_margin(0);
pPageInfo->set_right_margin(0);
pPageInfo->set_bottom_margin(0);
```

The units for all these methods are Logical Units, that is, hundreds of one millimeter.

Default values for a Document page size are the following:
```
, m_uLeftMargin(1500.0f)
, m_uRightMargin(1500.0f)
, m_uTopMargin(2000.0f)
, m_uBottomMargin(2000.0f)
, m_uBindingMargin(0.0f)
, m_uPageSize(21000.0f, 29700.0f)		//A4 21.0 x 29.7 mm
, m_fPortrait(true)
```

Probably you could do all this automatically by adding the code to the on-window-resize event handler (or something equivalent in android). I'm quite busy at this moment and I have not tested this solution. I will do it this weekend.


### 2. Do not display the score on a page-by-page basis, but vertically without any gaps

This is controlled by the View type used to display the score. Currently there are available three view types:

- k_view_vertical_book - displays the score as book pages, one page after the other in a vertical layout (i.e. Adobe PDF Reader, MS Word).

- k_view_horizontal_book - displays the score as book pages in horizontal (i.e. MuseScore, Finale, Sibelius)

- k_view_simple - displays the score without margins and gaps, and assume that it fits in one page. This is intended to create small images for controls (i.e. a combobox), to display small scores without margins a grey areas (gaps between pages) (i.e. LenMus Phonascus ScoreAuxCtrol)

In any case, its not complex to develop your own View format. So a solution could be to develop a view type oriented to display the score on a single system. The score would be displayed as a single line, scrolling in horizontal. And window size will not affect.

Nevertheless, using k_view_vertical_book you could try a simple method for removing the gaps. I have not tested it but probably you could avoid the gaps by displaying the score on a very very long page: set page height a big number, lets say 60 times current height.

```
pPageInfo->set_page_height(2000000.0f)
```
Again, I have not tested this solution. I will do it this weekend.


### 3. Enter the number of measures to display manually

I would discard this type of approach as it assumes that the score has measures (this is not always the case, see for instance well know pieces from Erik Satie) and that all measures are equal size (this is never the case, see for instance the difference in size from first measure and second measure in the picture you attached). The entered number of measures will have to refer to a 'standard measure mean width' and you will have to convert the number of measures to a desired page width.

Please, send feedback if you try any of this approaches.

**Comment by cecilios** [comment]
I've been doing some tests. The proposed idea works but the details were incorrect. For doing the tests I have modified the code in file lomse/examples/example-4-wx.cpp. Here is some working code:


### Avoiding the gaps between pages

I have modified method `void MyCanvas::open_file()` to force a very big page height. Modifications are marked with `-->`. This code works without problems:
```
void MyCanvas::open_file(const wxString& fullname)
{
    //create a new View
    std::string filename( fullname.mb_str(wxConvUTF8) );
    delete m_pPresenter;
    m_pPresenter = m_lomse.open_document(ViewFactory::k_view_vertical_book,
                                         filename);

    //get the pointer to the interactor, set the rendering buffer and register for
    //receiving desired events
    if (SpInteractor spInteractor = m_pPresenter->get_interactor(0).lock())
    {
        //connect the View with the window buffer
        spInteractor->set_rendering_buffer(&m_rbuf_window);

        //ask to receive desired events
        spInteractor->add_event_handler(k_update_window_event, this, wrapper_update_window);

-->     //set page height
-->     Document* pDoc = m_pPresenter->get_document_raw_ptr();
-->     ImoDocument* pImoDoc = pDoc->get_imodoc();
-->     ImoPageInfo* pPageInfo = pImoDoc->get_page_info();
-->     pPageInfo->set_page_height(2000000.0f);
    }

    //render the new score
    m_view_needs_redraw = true;
    Refresh(false /* don't erase background */);
}
```

### Automatically adjust the number of measures to fit the area size

I have modified method `void MyCanvas::OnSize()` to change page width as window width changes. Modifications are marked with `-->`: 
```
	void MyCanvas::OnSize(wxSizeEvent& WXUNUSED(event))
	{
		wxSize size = this->GetClientSize();
		create_rendering_buffer(size.GetWidth(), size.GetHeight());

-->     //adjust page size
-->     //Lets's define an arbitrary factor conversion: DIN A4 width (21,0 mm) will be
-->     //mapped to a window width of 1000px
-->     if (SpInteractor spInteractor = m_pPresenter->get_interactor(0).lock())
-->     {
-->         Document* pDoc = m_pPresenter->get_document_raw_ptr();
-->         ImoDocument* pImoDoc = pDoc->get_imodoc();
-->         ImoPageInfo* pPageInfo = pImoDoc->get_page_info();
-->         pPageInfo->set_page_width(LUnits(size.GetWidth()) * 21.0f);
-->         spInteractor->on_document_updated();  //This rebuilds GraphicModel and will generate a Paint event
-->     }
-->     else
        	Refresh(false /* don't erase background */);
	}
```

This code works very well to adjust the number of measures to fit the area size. But, unfortunately, the window can not be resized while the score is being played back, because the graphic model will be destroyed and, probably, highlight events are referring to no longer existing objects and cause a crash. I didn't investigate more to see if this is easy to fix. A bypass could be adding code in your app to forbid changing the window width while playback is going on.

I will leave this issue open for coding a definitive solution. I think the best would be to create a *free flow view* similar to a HTML browser. My first impression is that by copying the code of "vertical book view* and adding a couple of changes would be enough.

@juuk100 : Could you please provide me a short ordered list with the three/four more urgent open issues that you would like to be fixed?

**Comment by cecilios** [comment]
Closing this issue as nothing else can be done. I've filed a new issue (#122) for creating a free flow view that will behave in a similar way to a HTML browser: it will display the document in a single page, and will reflow / reformat it to always adapt to available page width.
