### ISSUE TITLE
UnitTest++ from packages-directory isn't used

### ISSUE THREAD

**Issue by hugbug** [lenmus/lomse#157]
In source code tree of Lomse under packages there is directory UnitTest++ containing a copy of UnitTest++ library (version 1.4).

The CMake configuration however searches UnitTest++ through the system and under no circumstances uses the copy from packages directory.

I recommend to remove UnitTest++ from packages.

**Comment by cecilios** [comment]
Thanks for spotting this. It is no used. I'll remove it. Long time ago I included in the repo all third party sources to facilitate building in Windows, as it was a nightmare for me to build there.

**Comment by cecilios** [comment]
Fixed by PR #158
