### ISSUE TITLE
Limit height of visual markers to page height

### ISSUE THREAD

**Issue by hugbug** [lenmus/lomse#226]
When the page height isn't enough to display just one system the new Lomse behaviour (recently introduced) is to draw the score with the page overrun. In older Lomse versions an error message was rendered instead. The new behaviour is clearly better but I'd like to point out some effect produced in the circumstances.

When visual markers are used they go the full length of the system (longer than page height). That becomes visible when scrolling to the next page:

![Screen Shot 2020-04-15 at 19 44 42](https://user-images.githubusercontent.com/3368402/79369827-e2100280-7f51-11ea-9835-7884ab44f74f.png)

![Screen Shot 2020-04-15 at 19 44 52](https://user-images.githubusercontent.com/3368402/79369920-079d0c00-7f52-11ea-94d1-11ec14c887c6.png)

Maybe if the height of markers is limited to page height that can be prevented? I understand that's a border case, which isn't worth much efforts. I just wanted to share the effect I've encountered.

**Comment by cecilios** [comment]
Thanks. I will look at this ASAP

**Comment by cecilios** [comment]
Instead of spending time in a bug bypass for trimming markers I've decided that it is better to solve the paper size problem and implement auto-scaling when the paper height is too small.

PR 228 will close this issue.
