### ISSUE TITLE
The binary size. Why is it so big?

### ISSUE THREAD

**Issue by herolover** [lenmus/lomse#232]
Good day! And thank you for the awesome library!

I'd like to use it in my Android app. But when I built it, I realized the lib size(under win x64) is around 41M. That is too big. I can't afford increasing APK size on that value.

Are there any workarounds to reduce the lib size? Exclude something?

**Comment by hugbug** [comment]
My executable is 5 MB and that's including Lomse and another library JUCE, which provides a whole cross-platform UI.

Your library probably includes a lot of debug information. That doesn't matter. Build your app first and then check the size.

**Comment by herolover** [comment]
Well, I'll try. But no, that build has no debug symbols:
```
CMAKE_BUILD_TYPE=Release
LOMSE_DEBUG=OFF
LOMSE_ENABLE_COMPRESSION=OFF
LOMSE_ENABLE_DEBUG_LOGS=OFF
LOMSE_ENABLE_PNG=OFF
```

**Comment by hugbug** [comment]
Every library (lib-file) contains a lot of debug information or other data used by linker and other tools such as symbols (names for every function etc.). It doesn't matter how big lib-files are. What matters is the size of your app.

How big is your APK?

**Comment by cecilios** [comment]
I never payed attention to library size!

I've been checking and in my 64bits Linux system the library liblomse.so.0.27.0 is only 12,2MB. I do not have at hand a Windows machine so I cannot check at this moment in windows.

> Are there any workarounds to reduce the lib size? Exclude something?

I never thought about that posibility but, for sure, parts of the code can be excluded. For instance, if you would only deal with MusicXML all other importers could be excluded. But, as said, the code is not currently prepared for this. It is necessary to analyse what to exclude, add some macros to define exclude options and to deal with them.

What is it going to be the main use? only to render scores? also for playback? interactive edition? other?

**Comment by cecilios** [comment]
Oh! Forget to say that my installed library contains debug information.

**Comment by herolover** [comment]
Thank you for your responses. And please accept my apologies for the concern.

The target app size increases by ~2M. So it's acceptable.

> What is it going to be the main use? only to render scores? also for playback? interactive edition? other?
Actually I only want to render some parts of the music score(i.e. chords and keys). No interactive, no playback, no even pages.

And again thank you for the awesome library!
