### ISSUE TITLE
API to manipulate instruments

### ISSUE THREAD

**Issue by cecilios** [lenmus/lomse#237]
From #208 the following requirements are identified:

- A way to hide unneeded instruments.
- A function to change the order of the instruments.
- Functions to hide/show/move instruments.

I will take the opportunity to review current methods and to start re-organizing, defining and documenting the API for score manipulation.

**Comment by cecilios** [comment]
@hugbug The _"hide/show"_ instrument operation is not related to the score model but it is an operation at presentation level. I mean, the operation does not change the score internal model, that still will contain the instrument, but tries to change how the score is rendered at display or audio levels.

Therefore, this operation should be moved to other place, perhaps at View level, at Sound Player level or at other places, and this should be studied and decided with care. Do you currently need this operation or it is enough for now if you can remove instruments from the score?

**Comment by hugbug** [comment]
Currently the workaround with manipulation of instruments works well for me.
Please take your time to define proper API.

Is it possible to have multipel views for the same score in Lomse? If yes, then it makes even more sense to show/hide instruments at the presentation level. That would make it possible to have one view with all instruments and another view with only one (or more) instruments. I don't need this in my app but can imagine such functionality in a more versatile score editor app.

**Comment by cecilios** [comment]
> Is it possible to have multipel views for the same score in Lomse?

Yes

> I don't need this in my app

Ok, thanks. Then I will postpone implementing these _"hide/show"_ methods in the API

**Comment by cecilios** [comment]
I've been looking at your code, related to this issue, and I think that PR #242 provides the necessary support methods to avoid having to deal with lomse library internals.

More or less this is the list of things to change in conpianist:
  
### Access to Document

Replace:
```c++
Document* doc = m_presenter->get_document_raw_ptr();
ImoDocument* imoDoc = doc->get_im_root();
```    
By

```c++
ADocument doc = m_presenter->get_document();
```


### Document methods

- All methods to set page margins now include the word `page` in the method name. Access to `ImoPageInfo` object is no longer needed:

    e.g., replace:
    ```c++
	ImoPageInfo* pageInfo = imoDoc->get_page_info();    
	pageInfo->set_top_margin(500);
    ```
    By
    ```c++
    ADocument doc = m_presenter->get_document();
	doc.set_page_top_margin(500);           //names changed by adding '_page'
    ```

- All getter methods have been renamed to suppress the `get_` prefix:	

    e.g., replace:
    ```c++
	m_docScale = imoDoc->get_page_content_scale();
	imoDoc->set_page_content_scale(1.0); // reset scale
    ```
    By
    ```c++
    ADocument doc = m_presenter->get_document();
	m_docScale = doc.page_content_scale();
	doc.set_page_content_scale(1.0);    // reset scale
    ```
	
- Access to document content and, in particular, to scores:

    e.g., replace:
    ```c++
	ImoScore* score = dynamic_cast<ImoScore*>(imoDoc->get_content_item(0));
	if (!score) return;
	m_scoreId = score->get_id();
    ```
    By
    ```c++
    ADocument doc = m_presenter->get_document();
	AScore score = doc.first_score();
	if (!score.is_valid()) return;
	m_scoreId = score.object_id();
    ```

- Get scoreId and advance user marks:

    e.g., replace:
    ```c++
	SpInteractor interactor = m_presenter->get_interactor(0).lock();
	Document* doc = m_presenter->get_document_raw_ptr();
	ImoScore* score = dynamic_cast<ImoScore*>(doc->get_im_root()->get_content_item(0));
	TimeUnits timepos = ScoreAlgorithms::get_timepos_for(score,
		loop.begin.measure > 0 ? loop.begin.measure - 1 : loopStart.measure - 1,
		loop.begin.measure > 0 ? loop.begin.beat - 1 : loopStart.beat - 1);
	loopStartMark = interactor->add_fragment_mark_at_note_rest(m_scoreId, timepos);
    ```
    By
    ```c++
	SpInteractor interactor = m_presenter->get_interactor(0).lock();
	ADocument doc = m_presenter->get_document();
	AScore score = doc.first_score();
	TimeUnits timepos = score.timepos_for(
			loop.begin.measure > 0 ? loop.begin.measure - 1 : loopStart.measure - 1,
			loop.begin.measure > 0 ? loop.begin.beat - 1 : loopStart.beat - 1);
	loopStartMark = interactor->add_fragment_mark_at_note_rest(m_scoreId, timepos);
    ```


### Score methods

- Access to instruments and remove an instrument. When an instrument is deleted it is automatically removed from any group. Therefore, you can now ignore groups when removing instruments. Groups will auto-reorganize and a group will be automatically removed when only one instrument left in it:

    e.g., replace:
    ```c++
	while (score->get_num_instruments() > 0)
	{
		ImoInstrument* instr = score->get_instrument(0);
		score->get_instruments()->remove_child(instr);
	}
    ```
    By
    ```c++
	while (score.num_instruments() > 0)
	{
        score.delete_instrument_at(0);

            //or
		AInstrument instr = score.instrument_at(0);
		score.delete_instrument(instr);
   	}
    ```

- Specific methods for re-ordering instruments have been added. You no longer need to save instruments and groups to restore the score before deleting it. See https://lenmus.github.io/lomse/classAScore.html#ad392638c71061468fb7ef0c53e1ae9a1

    e.g.:
    ```c++
	score.move_up_instrument(instr);
    ```



- Access to groups of instruments, remove group:

    e.g., replace:
    ```c++
	while (score->get_instrument_groups() &&
		score->get_instrument_groups()->get_num_items() > 0)
	{
		ImoInstrGroup* group = (ImoInstrGroup*)score->get_instrument_groups()->get_child(0);
		score->get_instrument_groups()->remove_child(group);
	}
    ```
    By
    ```c++
    score.delete_all_instruments_groups()

        //or
	while (score.num_instrument_groups() > 0)
	{
	    score.delete_instrument_group_at(0);

	        //or
		AInstrGroup group = score.instrument_group_at(0);
		score.delete_instrument_group(group);
	}
    ```



### Instrument methods

- Access to instrument MIDI info (**IMPORTANT**: API MIDI methods now require and return valid MIDI values (1 based) instead of 0 based values used by internal lomse objects):

    e.g., replace:
    ```c++
	ImoInstrument* instr = score->get_instrument(0);
	int midiChannel = instr->get_num_sounds() > 0 && instr->get_sound_info(0)->get_midi_info() ?
		instr->get_sound_info(0)->get_midi_info()->get_midi_channel() + 1 : 0;

    //or, more verbose:
	instr->get_num_sounds() > 0 
	ImoSoundInfo pSoundInfo = instr->get_sound_info(0)
	ImoMidiInfo pMidi = pSoundInfo->get_midi_info()
	int midiChannel = pMidi->get_midi_channel() + 1;
    ```
    By
    ```c++
    AInstrument instr = score.instrument_at(0);
	int midiChannel = instr.sound_info_at(0)->midi_info()->channel();

    //or, more verbose:
	instr.num_sounds() > 0
	ASoundInfo sound = instr.sound_info_at(0)
	AMidiInfo midi = sound.midi_info()
	int midiChannel = midi.channel();
    ```

- Change instr. names and abbrev:

    e.g., replace:
    ```c++
    instr->set_name(m_instrNames[num]);
    instr->set_abbrev(m_instrAbbrevs[num]);
    ```
    By
    ```c++
    instr.set_name_string(m_instrNames[num]);
    instr.set_abbreviation_string(m_instrAbbrevs[num]);
    ```
 
    
Hope this helps.

**Comment by hugbug** [comment]
Thank you for the new API and all the tips regarding my app.

Actually I don't need to delete instruments. All I wanted was to hide/unhide instruments (plus rearrange). In my app after the song and score are loaded the user can select an instrument to play. Then all other instruments from the score are hidden. The user can then select another instrument, then the previously hidden instrument must be shown again but all others must be hidden.

I used deletion of instruments as a workaround. With the new API the deleted instrument is probably gone for good and cannot be restored. Is this correct? In that case I need to load the score from the disk again, which I'd like to avoid because this costs time.

**Comment by cecilios** [comment]
Hide/unhide instruments is a fuctionality related to presentation and, thus, it is something that should be controlled at View level. I will include this functionality there.

> With the new API the deleted instrument is probably gone for good and cannot be restored. Is this correct?
Yes, that's correct. `AScore::delete_instrument()` removes the instrument from the score and deletes it. Lost forever!
