### ISSUE TITLE
Build on MinGW

### ISSUE THREAD

**Issue by chxiaoxn** [lenmus/lomse#238]
The MinGW comiler does not support `localtime_r`, but it does support `localtime_s`. I do not know how to write macro in C/C++. I just comment this part and use `localtime_s` directly. And it can be compiled successfully on MinGW.

I refer to you this page and the code

1. https://stackoverflow.com/questions/4605842/how-to-identify-platform-compiler-from-preprocessor-macros

2. https://github.com/lenmus/lomse/blob/f8149711e1d0b33c5097d0a7adc8023b7020524b/src/module/lomse_time.cpp#L74

**Comment by cecilios** [comment]
I can modify the sources and add a macro for MinGW compiler to select `localtime_r`, but first it is necessary to understand why MSVC is true if you are not using MSVC. I do not understand what is happening and need your help for this.

If you are doing:
```
mkdir build
cd build
cmake -G "Unix Makefiles" ..
make
```

the compiler should be g++ and cmake variable MVSC must be false, and it will set LOMSE_USING_MSVC to false. I do not understand why cmake variable MSVC is true in this context.

My understanding is that to build for MinGW you will need MinGW installed and available in your %PATH%. Then do:
```
mkdir build
cd build
cmake -G "MinGW Makefiles" ..
make
```
This should set camke valriable MSVC to false and valriable MINGW to true, and lomse will use `localtime_r`.

But if you need to use `cmake -G "Unix Makefiles" ..` then perhaps doing:
```
cmake -G "MinGW Makefiles" -DMSVC=OFF ..
```
could fix the problem. 

As said, for fixing this we need to understand why cmake variable MSVC is true when you are building for MinGW.

**Comment by chxiaoxn** [comment]
Thanks. I think using the `-DMSVC=OFF ` option is better.
