### ISSUE TITLE
A vector subscript out range Bug

### ISSUE THREAD

**Issue by hdhxt11** [lenmus/lomse#256]
WIN10 Visual Studio 2019 16.6

load file: m_pPresenter = m_lomse.open_document(k_view_vertical_book, "d:/QTDev/test-scores/unit-tests/grace-notes/215-graces-anacruxis-start.xml");

run at : Line 497 @  \src\graphic_model\engravers\lomse_slur_engraver.cpp

           if (m_fSlurBelow)
            {
 497               if (data[iCur].y < data[iPrev].y && data[iCur].y < data[i].y)
                {
                    //remove itCur
                    data.erase(data.begin() + iCur);
                    i = iCur;
                }

Debug Assertion Failed!

Program: D:\QTDev\Prjs\lomseV\build\Debug\tutorial_1.exe
File: d:\prog\VS2019\VC\Tools\MSVC\14.27.29110\include\vector
Line: 1501

Expression: vector subscript out of range

**Comment by cecilios** [comment]
Yes, bug confirmed.
I do not use Windows and this bug does not manifest in Linux. But by tracing subindices I've confirmed the bug. The fix is simple. Change line 493:  `for (size_t i=2; i < iMax; ++i)` :
https://github.com/lenmus/lomse/blob/5fd2f47c94f8ce79502851bd8dcc239238792827/src/graphic_model/engravers/lomse_slur_engraver.cpp#L491-L498
to
```
for (size_t i=2; i < data.size(); ++i)
```
Please, confirm this solves the problem for preparing a PR. Thank you.

**Comment by hdhxt11** [comment]
> Yes, bug confirmed.
> I do not use Windows and this bug does not manifest in Linux. But by tracing subindices I've confirmed the bug. The fix is simple. Change line 493: `for (size_t i=2; i < iMax; ++i)` :
> https://github.com/lenmus/lomse/blob/5fd2f47c94f8ce79502851bd8dcc239238792827/src/graphic_model/engravers/lomse_slur_engraver.cpp#L491-L498
> 
> 
> to
> ```
> for (size_t i=2; i < data.size(); ++i)
> ```
> 
> Please, confirm this solves the problem for preparing a PR. Thank you.

Very good! the Bug have been fixed.  

Another  bug:

file : src\platform\lomse_windows.cpp

  if (fontname == "BRAVURA")
     {
L 91--->        fullpath = m_pLibScope->fonts_path();
        fullpath += "Bravura.otf";
        LOMSE_LOG_INFO("key=%s, Path=%s", key.c_str(), fullpath.c_str());


line 91 , run after this line , fullpath=""  , WIN10 Visual Studio 2019 16.7.6

**Comment by cecilios** [comment]
> Very good! the Bug have been fixed.

Thank you. Closing this issue.

Please open a new issue for the new bug. Thank you!
