### ISSUE TITLE
bug report : can not get correct font path

### ISSUE THREAD

**Issue by hdhxt11** [lenmus/lomse#257]
file : src\platform\lomse_windows.cpp

if (fontname == "BRAVURA")
{
L 91---> fullpath = m_pLibScope->fonts_path();
fullpath += "Bravura.otf";
LOMSE_LOG_INFO("key=%s, Path=%s", key.c_str(), fullpath.c_str());

line 91 , run after this line , fullpath="" ( WIN10 Visual Studio 2019 16.7.6)

**Comment by cecilios** [comment]
Thank you. An issue per question/bug helps to simplify management.

Bravura.otf font is used for rendering musical symbols. But this font is not distributed in Windows and, therefore, when using lomse library this font must be installed.

Any Windows application using Lomse needs to specify the path were the Bravura font is instaled. The default path is specified when building the Lomse library, in lomse_config.h, variable `LOMSE_FONTS_PATH`, e.g.:
```
#define LOMSE_FONTS_PATH     "C:\Windows\fonts\"
```

This default path can be overriden in any application at lomse initialization or later, e.g.:

```
    LomseDoorway& lomse;
    lomse.set_default_fonts_path( bravuraFontPath );
```

So, the problem you are having is, probably, that nothing was specified in lomse_config.h when building lomse and also that your app didn't inform lomse about the default path to use. As a consequence, the fonts path is empty.

Please, check file lomse_config.h used when building lomse.

The recommended approach for solving this, is that your application informs lomse about the path for finding Barvura.otf font as, normally, as part of your application instalation it will have to install this font. In this way, your application will not depend on the options used for building lomse.

**Comment by hdhxt11** [comment]
> Thank you. An issue per question/bug helps to simplify management.
> 
> Bravura.otf font is used for rendering musical symbols. But this font is not distributed in Windows and, therefore, when using lomse library this font must be installed.
> 
> Any Windows application using Lomse needs to specify the path were the Bravura font is instaled. The default path is specified when building the Lomse library, in lomse_config.h, variable `LOMSE_FONTS_PATH`, e.g.:
> 
> ```
> #define LOMSE_FONTS_PATH     "C:\Windows\fonts\"
> ```
> 
> This default path can be overriden in any application at lomse initialization or later, e.g.:
> 
> ```
>     LomseDoorway& lomse;
>     lomse.set_default_fonts_path( bravuraFontPath );
> ```
> 
> So, the problem you are having is, probably, that nothing was specified in lomse_config.h when building lomse and also that your app didn't inform lomse about the default path to use. As a consequence, the fonts path is empty.
> 
> Please, check file lomse_config.h used when building lomse.
> 
> The recommended approach for solving this, is that your application informs lomse about the path for finding Barvura.otf font as, normally, as part of your application instalation it will have to install this font. In this way, your application will not depend on the options used for building lomse.

I see. Thank you!

**Comment by cecilios** [comment]
Could you solve the issue?

**Comment by hdhxt11** [comment]
> Could you solve the issue?

Yes!

**Comment by cecilios** [comment]
Ok. Thank you. Then I close this issue.
