### ISSUE TITLE
Remove RenderingBuffer from the API

### ISSUE THREAD

**Issue by cecilios** [lenmus/lomse#283]
The conversation in #282 suggests that, probably, the `RenderingBuffer` object should be a Lomse internal object, and any application using Lomse should just pass a ptr. to the image buffer and its size. The `stride` value should be something computed by Lomse as it has information for doing it.

I have to study this modification. Any comments and ideas about this and about any other possible changes to improve the API for rendering scores are welcome!

**Comment by ffAudio** [comment]
I wouldn't remove the option completely to supply a stride. It allows to draw in a sub area of the bitmap.

**Comment by cecilios** [comment]
Very good point! Thank you. 
It has also given me a clue as to how to do solve #12 ! Great!
