### ISSUE TITLE
Horizontal placement of objects attached to ImoDirection

### ISSUE THREAD

**Issue by dmitrio95** [lenmus/lomse#309]
Currently some types of auxiliary and relation objects are attached to `ImoDirection` staff objects on reading a MusicXML score. This helps to describe objects that may be not attached to any note but this also has certain implications on engraving of such objects. Since `ImoDirection` is a staff object it is always being engraved as an object not attached to a note, and engravers of the objects attached to it cannot align the corresponding shapes to noteheads or even chord boundaries in general. As an illustration, here is an image of different configurations of wedges and work-in-progress pedal lines if they would be aligned the same way as wedges are: 
![изображение](https://user-images.githubusercontent.com/6000747/129497555-9c9391db-ac10-450e-9592-87afd9978db9.png)

In the image above wedges which start or end at measure borders are colliding with the corresponding barlines — but not in the first measure where the wedge is aligned approximately with the left edge of the accidental. Other attachment points look better but engravers are still unable to choose noteheads, chord edges or other reasonable locations to align created object shapes with them. Still it would be desirable, for example, to align pedal and wedge start points with the corresponding notes or choose wedge end locations so that they don't collide with a barline. Changing shape location for `ImoDirection` is also probably not a good option since it would break engravers that rely on the current invisible direction shape location (for example the engraver for coda and segno marks).

To resolve this issue I see at least the following options:
1. Attach wedges (and pedals) to the closest notes in the internal model. This is the way this is handled for octave shifts or, since my previous pull request on a similar issue (#279), for dynamic marks.
2. Provide engravers of the objects attached to directions with some sort of information on locations of note and/or barline shapes. This information may be in the form of references to actual shapes or in the form of a generic information about coordinates of columns and some important points inside them (like notehead edges). Then engravers could decide placement of the corresponding shapes based on actual coordinates of the nearest staff objects and better horizontal placement algorithms could possibly be implemented.

The first option seems simpler and is already applied for certain object types, but the second option adds much more flexibility both for engraving and for designing the internal model for these types. Therefore I am in favor of exploring possibilities for the second solution but I may be missing something in my considerations. Would this solution make sense for this issue, or are there perhaps some other options that I may be missing?

**Comment by cecilios** [comment]
Thank you very much for raising this. I do appreciate it. Certainly, currently there are problems with spanning notations attached to `ImoDirection` objects. And deciding on a solution deserves adequate attention. I will think a little on all this and post then my comments.

**Comment by cecilios** [comment]
These is the reasoning and the conclusions of a first brainstorming:

To me, the internal model (IM) should be an abstract model of the score: it will capture the semantics and must be valid for any purpose. Thus, the IM should not be biased to facilitate any specific process (e.g. engraving). Therefore, the decision of attaching to Notes or Directions a spanning notation should not be based on engraving but on other considerations.

Spanning notations attached to a Direction define a relationship (thus, it should be modeled by RelObjs) that affects to all the notes contained between the start and end Directions. But as they affect the notes inside, it is equivalent to attach the relation the the start and end notes. Therefore, from the IM point of view I have no arguments to favor of any of your two proposed options: both seems equally valid to me. Thus, your option 1 of moving these relationships to start/end notes is acceptable.

But even by attaching the RelObjs to notes, the ‘vision’ RelObj engravers have is very narrow, reduced to the shapes for the objects in the relation. There are no methods to identify and access neighboring shapes.

Thus option 1 is, as you said, simpler and cheaper but probably not enough for improving layout in future. Also, my feeling is that it would be better to keep the IM aligned with the most advanced independent score models that Lomse will target to support: MusicXML for now and, in future, MNX. And if Lomse follows the MusicXML model, some spanning notations will be attached to Directions, not to notes. And, in MNX, there will also be some notations attached to Directions not to notes (the 'spanning directions', e.g.: octave-shift, wedge, pedal, ...). Thus, again, as with MusicXML, in MNX some spanning notations will be attached to Directions, not to notes.

Therefore, my vote is to follow the MusicXML/MNX model in the IM and, thus, to keep some spanning notations attached to Directions, not to notes. This goes to your option 2: provide engravers for RelObjs attached to Directions with additional information, at least with information about boundary objects (prev and next StaffObj shapes).

And I can not see more options. Thus if we choose option 2, what additional info should receive the engravers and how to get and provide this information?

Reviewing the engraving process, when a RelObj engraver is requested to create the shapes, StaffObjs are already engraved and their shapes have been added to the BoxSystem. Thus the BoxSystem can be explored to locate all relevant shapes around the ImoDirection shape. The BoxSlice objects contain the StaffObj shapes correctly positioned, and the BoxSystem contains the BoxSlices. Thus, the simplest Lomse modification would be to modify RelObj engravers to receive not only the parent StaffObj and its shape, but also the BoxSlice in which this shape is included. The BoxSystem can trivially be accessed from the BoxSlice. With this info, now the engraver can navigate the BoxSlice to locate the ImoDirection shape and use neighbouring shapes if needed. And it will also have access to all shapes in the system.

This change is general and could be useful for all engravers for RelObjs. Probably some helper methods should be added to BoxSlice / BoxSystem for engraving related tasks, such as to locate a shape and return an iterator to it; and to provide methods accepting that iterator for traversing the shapes forward/backwards to get neighboring shapes.

The required changes are very simple and could be worth exploring this solution. How do you see this?

I would do this in two steps:
1. Provide RelObj engravers with the BoxSlice
2. Try to use it in a RelObj engraver (e.g. pedal lines or wedges) to validate the approach and get conclusions for future changes.

If you don't feel confident to do step 1, I can take that task.

-----
I attach some notes that describe the layout process, in case they can be of help to you. They are part of my internal documentation and, as all documentation, could be not totally up to date in small details.
[Lomse_Hacking_Guide--Layout_and_engraving--Score_layout--Layout_algorithm_at_high_level.pdf](https://github.com/lenmus/lomse/files/6993738/Lomse_Hacking_Guide--Layout_and_engraving--Score_layout--Layout_algorithm_at_high_level.pdf)
[Lomse_Hacking_Guide--Layout_and_engraving--Score_layout--Engraving_AuxObjs_and_RelObjs--Overview.pdf](https://github.com/lenmus/lomse/files/6993739/Lomse_Hacking_Guide--Layout_and_engraving--Score_layout--Engraving_AuxObjs_and_RelObjs--Overview.pdf)
[Lomse_Hacking_Guide--Layout_and_engraving--Score_layout--Engraving_AuxObjs_and_RelObjs--Engraving_RelObjs.pdf](https://github.com/lenmus/lomse/files/6993741/Lomse_Hacking_Guide--Layout_and_engraving--Score_layout--Engraving_AuxObjs_and_RelObjs--Engraving_RelObjs.pdf)

**Comment by dmitrio95** [comment]
Thanks for your answer! I agree that some engravers may need more context beyond their parent object so that might indeed be the reason to provide that context to engravers regardless of choices with the structure of the internal model. I thought a separate data structure would be necessary for that but if everything that is needed can be obtained from the existing `BoxSystem` that is even better.

I would add though that if we choose to attach certain things to `ImoDirection` then some `AuxObj` engravers will need this context information too. Standalone pedal marks can be one example of that: as discussed in #272, we might need separate types for both pedal marks (paired or not) and pedal lines, and it would be logical to attach them to the same type of objects. If we choose to follow the MusicXML model here and attach them to Directions then the engraver for pedal marks would need an information about the next note to align with it properly.

> If you don't feel confident to do step 1, I can take that task.

Well, I can do this as well so I can take both steps or only some of them if you prefer.

> I attach some notes that describe the layout process, in case they can be of help to you.

Thanks, that will indeed help me understand the process better!

**Comment by cecilios** [comment]
> I thought a separate data structure would be necessary for that but if everything that is needed can be obtained from the existing BoxSystem that is even better.

In the Graphic Model (GM) each GmoBox object contains a std::list with the shapes contained in that box, in engraving order. GmoBoxSystem contains only a few shapes: those associated to the instruments in that system (the staff lines, instrument names, instrument brace/brackets, and little else). But BoxSystem contains BoxSlices (probably no shapes inside) who in turn contains BoxSliceInstruments and this contains BoxSliceStaff with all the shapes for that slice of the staff. Please find here some documentation about the GM; it is a very old document but it is still valid:  [graphic-model.zip.txt](https://github.com/lenmus/lomse/files/7001120/graphic-model.zip.txt)

Perhaps the BoxSystem is not a friendly object for locating the shapes relevant to an engraver. So, probably, what is needed are member methods in the GmoBox objects to facilitate the life to engraver objects. But I do not discard the idea of creating an specific data structure specific for an engraver; please feel free to create it if it is a better solution. But,probably, but learn about what is needed and see how to instantiate it, probably it will be necessary to navigate the GmoBoxes and the contained shapes. So, to gain knowledge before taking a decision about creating specific structures, I would first explore the feasibility of using the BoxSystem, to decide on the need of adding more methods oriented to locate a shape of interest or to traverse the shapes, as well as other requirement to improve the GM for engraving tasks. Your work on the pedal engravers will give you a deeper understanding of the needs. And then a better informed decision will be taken.

> some AuxObj engravers will need this context information too

Certainly. And the solution could be the same than for RelObjs: to pass them the BoxSystem or then decided ad-hoc structure. Feel free to make any changes you think are necessary.

> Well, I can do this as well so I can take both steps or only some of them if you prefer.

I prefer that you do it, as I trust you and I would prefer to stay focused on my current task: replacing the spacing algorithm to improve and solving all issues detected related to horizontal spacing. But, in any case, please feel free to ask for information and documentation as well as to discuss any ideas you have. Thank you!

> Thanks, that will indeed help me understand the process better!

Sorry for not having ready to publish documentation about Lomse internals. I have my notes but not in a friendly format so that they can be shared or uploaded to the lomse repo and, in any case, before doing it it will be necessary to review and update all this documentation, and to decide on the most appropriate format. Please feel free to ask for documentation about any specific issue of your interest. I will post the available documentation, if any. And if not available, it will be a good opportunity for creating it.

**Comment by dmitrio95** [comment]
OK, I will take this task then, will post updates when I get something ready.

Concerning the documentation, I find it useful because it helps to understand how certain things are intended to work or why certain decisions were taken. For me it's fine that documentation on some areas is not available because I will need to figure out most of things from the code anyway, but If I have questions on the reasoning of something I will certainly ask.

**Comment by cecilios** [comment]
A usefull tool for understanding how to access the shapes needed by the engraver from the BoxSlice that contains the ImoDirection is to generate a dump of the graphic model. For this, once the GM is built and the score is displayed just do something as: 

```
GraphicModel* pGM = pInteractor->get_graphic_model();
stringstream out;
int pages = pGM->get_num_pages();
for (int i=0; i < pages; ++i)
{
    out << "Page " << i
        << " ==================================================================="
        << endl;
    pGM->dump_page(i, out);
}

//display or save the dump
```

For instance, for this score  [wedge.xml.txt](https://github.com/lenmus/lomse/files/7007067/wedge.xml.txt)

![image](https://user-images.githubusercontent.com/5238679/129895240-f4396ab1-5b78-49a4-86e9-0445ffbd0319.png)


Generates this dump:

```
Page 0 ===================================================================
                    org.x        org.y     size.x      size.y
-------------------------------------------------------------
0 [  1] box-doc-page         0.00,       0.00,   21000.00,   29700.00
  1 [  2] box-docpg-cont.   1500.00,    2000.00,   18000.00,    2735.00
     2 [  6] box-score-page    1500.00,    2000.00,   18000.00,    2735.00
        3 [ 10] box-system        1500.00,    2000.00,    9159.03,    2735.00
           4 [ 50] staff          [0]   3044.26,    3000.00,    7614.77,     735.00
           4 [ 52] text           [0]   1500.00,    3039.44,    1364.26,     407.69
           4 [ 18] barline        [0]   3044.26,    3007.50,      27.00,     720.00
           4 [  7] box-slice         3044.26,    2000.00,    4584.39,    2735.00
              5 [  8] box-slice-intr    3044.26,    2000.00,    4584.39,    2735.00
                 6 [  9] box-slice-staff, idxStaff=0
                    7 [ 23] clef           [0]   3179.26,    2733.50,     497.00,    1302.00
                    7 [ 33] key            [0]   3856.26,    3000.00,       0.00,       0.00
                    7 [ 54] time           [0]   4036.26,    3002.50,     319.00,     731.00
                    7 [ 32] invisible      [0]   4805.26,    3007.50,       0.00,     720.00
                    7 [ 38] (6)note           [0]   4850.26,    3274.50,     219.00,     723.00, s=630.00
                    7 [ 38] (6)note           [0]   5782.05,    3274.50,     219.00,     723.00, s=630.00
                    7 [ 32] invisible      [0]   6668.85,    3007.50,       0.00,     720.00
                    7 [ 38] (6)note           [0]   6713.85,    3274.50,     219.00,     723.00, s=630.00
                    7 [ 18] barline        [0]   7601.64,    3007.50,      27.00,     720.00
                    7 [ 59] wedge          [0]   4805.26,    2557.50,    1863.59,     270.00
           4 [  7] box-slice         7628.64,    2000.00,    3030.39,    2735.00
              5 [  8] box-slice-intr    7628.64,    2000.00,    3030.39,    2735.00
                 6 [  9] box-slice-staff, idxStaff=0
                    7 [ 32] invisible      [0]   7628.64,    3007.50,       0.00,     720.00
                    7 [ 38] (6)note           [0]   7880.64,    3274.50,     219.00,     723.00, s=630.00
                    7 [ 38] (6)note           [0]   8812.44,    3274.50,     219.00,     723.00, s=630.00
                    7 [ 32] invisible      [0]   9699.23,    3007.50,       0.00,     720.00
                    7 [ 38] (6)note           [0]   9744.23,    3274.50,     219.00,     723.00, s=630.00
                    7 [ 18] barline        [0]  10632.03,    3007.50,      27.00,     720.00
                    7 [ 59] wedge          [0]   7628.64,    2557.50,    2070.59,     270.00
```


Notice the invisible shape  for the ImoDirection with the wedge after the time signature shape, and again a new invisible shape for the ImoDirection with the end of the wedge, before the note. The last StaffObj shape in first measure is the barline shape and after it the shapes for AuxObjs/RelObjs are added to the list. So after the barline shape it is the wedge shape.

Thus if the engraver receives the BoxSlice associated to each StaffObj in the relation, it will have access to the shapes for the StaffObjs before and after the ImoDirectio and well as any other shape.

The knowledge to traverse the GM should not be placed on the engravers but in the GM. Thus, I foresee a method to locate a shape as well as methods to locate shapes after or before a given shape.

Hope this helps.

**Comment by cecilios** [comment]
It is also possible to force Lomse to render the bounding box for GmoBoxes as well as for the shapes.

To draw the bounding box of all shape objects it is necessary to set that option, at Lomse library level, before generating the GM. To do it:

```
LomseDoorway& lib = ...
LibraryScope* pScope = lib.get_library_scope();
pScope->set_draw_shape_bounds(true);
```
![image](https://user-images.githubusercontent.com/5238679/129948061-73a887ef-4d0e-4924-a3e2-4f24280aafc5.png)


To draw the bounding box of all GmoBox objects of a certain class you can request it via the interactor, specifying the box types. To do it:

```
if (SpInteractor spInteractor = m_pPresenter->get_interactor(0).lock())
{
    spInteractor->reset_boxes_to_draw();
    spInteractor->set_box_to_draw(GmoObj::k_box_slice);
}
```
![image](https://user-images.githubusercontent.com/5238679/129948096-0da20734-46c8-4546-8661-f7370bb8e0af.png)



And to remove the boxes:
```
   spInteractor->reset_boxes_to_draw();
```

**Comment by dmitrio95** [comment]
I have investigated a structure of the graphical model, and it turns out that each staff object shape actually contains a reference to its parent `GmoBoxSliceStaff`, so there is no need to pass any additional information to the engravers. I will open soon a pull request with a possible implementation of iterating over the nearest shapes.

**Comment by cecilios** [comment]
> it turns out that each staff object shape actually contains a reference to its parent GmoBoxSliceStaff

I didn't remember. But certainly this simplifies accessing the neighboring shapes!

**Comment by cecilios** [comment]
I'm going to close this issue since there is nothing actionable right now and PR #317 somehow solved the issue. Anyone should feel free to continue to use this issue to document ideas and findings or new questions, or just reference this issue in pull requests. It can be re-open if necessary.
