### ISSUE TITLE
Editing a Score

### ISSUE THREAD

**Issue by highapect** [lenmus/lomse#325]
I am interested in using your software to a) read in the contents of an ABC notation file b) render it to the screen and c) have the user mark the beginning and end of phrases the user identifies. And d) each of the phrases would be written to a separate ABC Notation file and be written to disk.  For instance, in a traditional fiddle tune he/she would mark the beginning and end of Part 1 of the A section, then part 2 , then the beginning and end of part 1 of the B section followed by part 2. of the B section.  My question is when a user selects a particular note, I would receive an event identifying a (row column) location of the mouse click in the bitmap.  How would I identify the location in the Score where that particular note occurs. 

The user would then be able to loop each of the sections one at a time in order to learn the tune by ear (the score would be hidden at that point).  The only question I have is identifying the location in the score based on where in the rendered bitmap the user clicked.   I haven't begun working with the actual code but the documentation looks excellent.  In addition, the cross platform work looks great, too.  Thanks a bunch.

**Comment by cecilios** [comment]
> a) read in the contents of an ABC notation file

Currently Lomse does not have an importer for ABC notation. Probably it is not complex to write one. Lomse now have importers for LDP, MusicXML and some initial code for MNX. All of them follow a similar approach that probably can be used for ABC notation.

> b) render it to the screen and

Once the file is imported it is converted into an internal format, and rendition is totally supported (some music notation still missing).

> c) have the user mark the beginning and end of phrases the user identifies. And d) each of the phrases would be written to a separate ABC Notation file and be written to disk. For instance, in a traditional fiddle tune he/she would mark the beginning and end of Part 1 of the A section, then part 2 , then the beginning and end of part 1 of the B section followed by part 2. of the B section.

This will require to write an ABC notation exporter. Again, probably it is not complex to write one. It is just traversing the internal model and generating the desired output. The LDP exporter can be used as a model. Or your application would do it it.

> My question is when a user selects a particular note, I would receive an event identifying a (row column) location of the mouse click in the bitmap.
> How would I identify the location in the Score where that particular note occurs.

Interaction with the bitmap/score is totally supported. Depending on dynamically configurable options (edition enabled/disabled, task mode, etc.) a mouse click would generate different events, e.g. an `EventMouse` event (see https://lenmus.github.io/lomse/classEventMouse.html) that provides information about the pointed object (note, rest, etc.). Once the clicked object is identified you can do many things. For instance, place a visual mark on the score to give feedback to the user (see https://lenmus.github.io/lomse/classFragmentMark.html) and instantiate a cursor (a kind of iterator) for traversing the score from that point.

Current documentation does not give much information about interaction with the score. But if you are interested I could write some documentation in two/three weeks.

**Comment by cecilios** [comment]
Closing this old issue because it has not had recent activity.
