### ISSUE TITLE
Change Lomse license to MIT

### ISSUE THREAD

**Issue by cecilios** [lenmus/lomse#341]
To me, current BSD license is clear and very simple. But some people believe that it is open to arguments about patents. The Apache license was the BSD but to avoid these doubts, text was included to clarify that they also give permission to use the patents. We could move to the Apache license but it is a long text and, like most contracts, it is scary to read and to understand. Also, the more text is added, the more doubts and interpretations about things not explicitly stated. Therefore I prefer instead the MIT license. It is widely used and extremely simple.

In order to proceed with this change, I need explicit approval from the people that have contributed code to this repo:

@dmitrio95
@ffAudio
@hugbug
@jamescauwelier
@kolewu

To agree to re-licensing, please comment to this issue with something as:

```
I agree and I license past contributions to Lomse under the MIT license.
```

Thank you!

**Comment by kolewu** [comment]
I agree and I license past contributions to Lomse under the MIT license.

**Comment by hugbug** [comment]
I agree and I license past contributions to Lomse under the MIT license.

**Comment by dmitrio95** [comment]
I agree to the license change, and I license my past contributions to Lomse under the MIT license.

**Comment by ffAudio** [comment]
Thank you @cecilios for all your work. I think that is a great change.

I agree and I license past contributions to Lomse under the MIT license.

**Comment by jamescauwelier** [comment]
I agree and I license past contributions to Lomse under the MIT license.

**Comment by cecilios** [comment]
Thank you everybody! I appreciate your support and your contributions to the project.
I will proceed with the change and will close this issue with the PR.
