### ISSUE TITLE
Support tablature notation

### ISSUE THREAD

**Issue by ayyb1988** [lenmus/lomse#344]
staves score parsing and rendering no problem.
 but how to guitar score parsing rendering
![gutascore](https://user-images.githubusercontent.com/7148115/158514257-ccf39c4d-b1e3-4438-81fa-6ad9dc1da221.png)
![statvasscore](https://user-images.githubusercontent.com/7148115/158514261-2c10e504-751a-478b-be58-76a6fd8820fa.png)

**Comment by cecilios** [comment]
MusicXML tablature notation is not yet supported, although the additional required code is minimal. But until now nobody required this. I'm at the moment working in other commitments, but if you would like to use Lomse and your app needs tablature, I could start working on this in  a few days.

**Comment by ayyb1988** [comment]
Thank you very much. I apply lomse to my application, I need to support guitar tabs, it would be great if I could get your help

**Comment by cecilios** [comment]
OK. I will start with this probably by next week

**Comment by ayyb1988** [comment]
Thanks again

**Comment by cecilios** [comment]
After merging PR#346 Lomse now renders tablature notation. But the PR does no't add support all notation related to tablature and guitar. MusicXML supports a lot of technical notations for many instruments, but as many notation applications, Lomse only renders the most common ones. Please, fell free to request support for a specific technical mark by opening an issue.
