### ISSUE TITLE
How to fetch note information from internal model?

### ISSUE THREAD

**Issue by AndreasKoettl95** [lenmus/lomse#349]
Dear Devs,

I'm trying to fetch information about each note in a score. I want to know the step, the octave, and any other information that is provided in the score. But I can't figure out how to do it.

I'm new to this library, and I know there is this ImoNote class, there are enums for steps and octave, so I assume the information is somewhere in the internal model, but I don't know how to fetch it.

Background if it does matter:
I want to analyze, what a musician has to do, to play a certain note. For example on a guitar, what fret needs to be pressed, how many strings are involved, how long is the duration of this note, etc. And according to this information, I want to modify the document, e.g. remove the next note etc. and update the render output.

Hope you can help me out.

Thanks!

**Comment by cecilios** [comment]
This is an example for traversing all notes in the order they will be played an accessing notes information:

```
    Presenter* m_presenter = m_lomse.open_document(...):
    ADocument doc = m_presenter->get_document();
    AScore score = doc.first_score();
    ImoScore* pScore = score.internal_object();

    StaffObjsCursor cursor(pScore);
    while(!cursor.is_end())
    {
        ImoStaffObj* pSO = cursor.get_staffobj();
        if (pSO->is_note())
        {
            ImoNote* pNote = static_cast<ImoNote*>(pSO);
            pNote->get_voice();
            pNote->get_step();
            pNote->get_octave();
            pNote->get_fpitch();                //FPitch. Ignores fractional part of actual accidentals
            pNote->get_midi_pitch();            //MidiPitch
            pNote->get_playback_duration();     //playback duration: nominal duration for playback
            pNote->get_event_duration();        //event duration: real duration for playback
            pNote->get_playback_time();         //playback time: on-set time for playback
        }

        cursor.move_next();
    }
```

**Comment by AndreasKoettl95** [comment]
Sorry, for not letting you know by now, but this is exactly what I need.  
Thank you for your help and fast response!

I will continue using this library for my project. It seems to already provide most of the things that I need, at least in some way. I just have to figure out how to use it.

From my perspective, this issue can be closed, thank you.
