### ISSUE TITLE
Beginning/end number of the measures in a system

### ISSUE THREAD

**Issue by cecilios** [lenmus/lomse#382]
@npiegdon
In discussion #377 it was requested information about how to get the beginning/end number of the measures in a system

This request is difficult to answer without referring to an instrument. Take into account that in polymetric music  (music in which not all instruments have the same time signature) the measure number is not a common value for all instruments and, thus measure numbers in a system will depend on which instrument you refer to. For instance, in the typical example from Mozart's opera _Don Giovanni_, how many measures are in this system? two or three?

![image](https://user-images.githubusercontent.com/5238679/198365815-2364185c-b87c-4341-8b18-589130d904e0.png)

Thus, it is necessary to specify not only the system number but also an instrument. But assuming that your app will only display the piano part, and the remaining parts, if any, will be hidden, in your app `iInstr` will be always 0.

```
GmoBoxSystem* pSystem =  ...
int iFirstMeasure = pSystem->get_first_measure(iInstr);    //0..n-1, referred to current layout
int numMeasures = pSystem->get_num_measures(iInstr);
```
**Important**. Method `get_num_measures()` is not currently defined. But is is just to lines of code so I will add it in a coming PR.

Let me know if this solves your needs.

**Comment by npiegdon** [comment]
Well, that's terrifying. 😅

Having to specify an instrument is a good strategy and should work for my purposes.  Thanks!

**Comment by cecilios** [comment]
PR #385 adds the `get_num_measures()` method.

**Comment by cecilios** [comment]
I am closing this issue as it appears to be resolved. If you believe things are still unresolved please let me know and I can reopen if needed.
