### ISSUE TITLE
Baseline of each staff

### ISSUE THREAD

**Issue by cecilios** [lenmus/lomse#384]
The last question I find in discussion #377 is about how to get the baseline (or some other anchor point) of each staff in the system.

Opening this issue as a remainder to answer this question.

**Comment by cecilios** [comment]
A simple way to get this information is by asking `GmoBoxSystem` for the staff shapes, and then requesting the staff bounding box (or its origin):

```
GmoBoxSystem* pSystem = ...
GmoShapeStaff* pStaff = pSystem->get_staff_shape(int iInstr, int iStaff);
UPoint origin = pStaff->get_origin()
```

As always, origin is relative to GmoBoxPage origin. But as `FreeFlowView` has only one page with origin at (0, 0), the returned staff origin can be used as absolute coordinates for `FreeFlowView`.

**Comment by cecilios** [comment]
@npiegdon  Did the answer solved your needs? Can I close this issue?

**Comment by npiegdon** [comment]
Yes, this should be perfect, thanks!  (And I am hoping to have a chance to confirm that, starting in just a couple weeks.)

**Comment by cecilios** [comment]
No problem. I'll keep it open until you can test and confirm.

**Comment by cecilios** [comment]
I am closing this issue due to lack of any feedback. So I assume the issue is solved
