### ISSUE TITLE
How to realize the rendering of numbered musical notation?

### ISSUE THREAD

**Issue by ayyb1988** [lenmus/lomse#386]
How to realize the rendering of numbered musical notation ,Based on the musicxml protocol.

![AmazingGraceNumberedMusicalNotation](https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/AmazingGraceNumberedMusicalNotation.png/800px-AmazingGraceNumberedMusicalNotation.png)

**Comment by cecilios** [comment]
To my knowledge MusicXML does not support this notation. Could yoy share a MusicXML file for that score?

**Comment by cecilios** [comment]
Uhmmm, perhaps you are asking to render a MusicXML file as numbered musical notation (Jianpu, 简谱). If that was your question, Lomse can not do it.
