### ISSUE TITLE
Playback very slow for 3/8 tempo

### ISSUE THREAD

**Issue by juuk100** [lenmus/lomse#69]
I found the problem through several tests.
The point is that it does not handle the following values properly.

#MusicXML
<time>
           <beats> 3 </ beats>
           <beat-type> 8 </ beat-type>
</ time>

#LDP
(time 3 8)

6/8 time is processed normally, but if it is 3/8, it plays slowly.

**Comment by cecilios** [comment]
I'm trying to reproduce but not sure. Could you please send me the 6/8 file you are using for comparison?

**Comment by cecilios** [comment]
Juuk, the bug is confirmed. It is not necessary that you send me the 6/8 file. Hope to fix it very soon.

**Comment by cecilios** [comment]
I've retitled this issue for clarity.

**Comment by cecilios** [comment]
Fixed by PR #76
