### ISSUE TITLE
Highlight is not synced. when moving to next page.

### ISSUE THREAD

**Issue by cecilios** [lenmus/lomse#73]
juuk100 reports that:

>   And when the score is highlighted, if the page goes to the next page, the highlight position and the score do not match.
(tested with fur-elise.xml)

I've not been able to reproduce this. What I have noticed is that the syncing can be lost for a small fraction of time while dragging the view for moving to another page. I will open an issue just in case, for investigating more. If you could do more tests and determine the conditions in which the lost of syncing. takes palce would be great for focusing the problem.

**Comment by juuk100** [comment]
Attach a test video.

The following is my file open source code.

std::string filename = FileUtils::getInstance()->fullPathForFilename("bach-invention.xml");
delete m_pPresenter;
m_pPresenter = m_lomse.open_document(ViewFactory::k_view_simple, filename);

k_view_simple, k_view_vertical_book
These two are the same result.

[test.zip](https://github.com/lenmus/lomse/files/1305682/test.zip)

**Comment by cecilios** [comment]
Thanks for the video! The issue is clear to me now and I was able to reproduce the problem. Hope to fix this soon.
