### ISSUE TITLE
Default MIDI channel when no midi information in file

### ISSUE THREAD

**Issue by cecilios** [lenmus/lomse#81]
Instead of assigning channel 0 to instruments without MIDI settings, assign a different channel to each score-part.

Related to #77 (already closed)

Rationale:
The channels are assigned to score-parts according to the settings specified in the MusicXML (or LDP) file. When a part has no midi settings, it is assigned to channel 0. Therefore, in scores with multiple parts and no midi information, all parts get assigned to the same channel.

In these cases, a user application wishing to assign a different MIDI instrument to each score part, will be prevented of doing it just by changing the sound assigned to each MIDI channel in the MIDI sound generator. Instead, the only possibility would be more complex as it will require to modify the MIDI data in the Lomse internal model.
 
Instead of assigning channel 0 to instruments without MIDI settings, it would be nice to assign a different channel to each score-part. 

To think:
	- should channel 9 (percussion, MIDI channel 10) also be used? 
	- what to do if more than 15 instruments?

Any thoughts welcomed!

**Comment by cecilios** [comment]
@juuk100
I've been studying this problem and the solution is not complex. I hope to fix this very soon. But reviewing this issue, I feel the convenience of dealing also with the MIDI port in the sound events. The port was not taken into account until now!. This will imply changing the API for adding an additional 'port' parameter to all MIDI events:

```
    void program_change(int port, int channel, int instr)
    void voice_change(int port, int channel, int instr)
    void note_on(int port, int channel, int pitch, int volume)
    void note_off(int port, int channel, int pitch, int volume)
```
By providing port information the user application will have full information for dealing properly with midi.
 What do you think? Is this is acceptable?

**Comment by juuk100** [comment]
Does the MIDI port mean that each port contains instrument information or part information?
If it is correct, it does not seem to be a problem.
If the musicxml file does not have MIDI information anyway, I think the channel should be separated even by the part information.
Even if the API changes, there is no problem in applying to my application.

If the meaning of the MIDI port is different, please describe it again.

**Comment by cecilios** [comment]
The MIDI port refers to the MIDI device (real or virtual) to use for generating the sound. Each port has 16 different channels that can be used to pass data. The sound card of a computer normally has only one MIDI sinthesizer and thus MIDI port information is not normally used.

Once the MIDI device is selected (by the midi port information), the generated sound is controlled by the MIDI program (1...128). This allows the selection of one of 128 possible sounds. For expanding the number of different instrument sounds which may be specified, sound are grouped in 'banks' (128 sounds per bank). The MIDI bank information selects the bank (up to 16,384 banks of 128 sound each). Once the bank is selected, the MIDI program selects the sound in the bank (1-128).

The sound card of a computer normally has only one MIDI sinthesizer with only one bank of sounds. Therefore, MIDI port and MIDI bank information is usseless. But software for dealing with MIDI and audio, such as JACK, can deal with multiple MIDI ports and the devices (real or virtual) connected to those ports can deal also with different sound banks.

Until now, Lomse assumed only one MIDI port and no MIDI banks. Therefore, Lomse only deals with channels and programs. But MusicXML allows to assign to each score part (instrument) a midi device (the midi port to use), a midi channel, a midi bank and a midi program. An for fully supporting MusicXML and MIDI, it would be necessary to modify the Lomse MIDI API for including port and bank information.

Therefore, the events related to selecting the sound source (program_change & voice_change events) will include two additional parameters: port and bank. And the events for producing sound (note_on & note_off events), will include also the port. The voice_change even I think is the same as the program_change event (I have to check this) and, it true, one of them will be removed.

The user application can always ignore these new parameters.
