### ISSUE TITLE
How can I do key transposition?

### ISSUE THREAD

**Issue by juuk100** [lenmus/lomse#89]
I would like to change the key to score.

Please let me know how.

**Comment by cecilios** [comment]
I'm not sure what you are asking. I have thought of three possibilities:

1. My first interpretation is the literal one: how to change the key signature. Deleting and inserting a key signature is done by using edition commands (see https://lenmus.github.io/lomse/document-edition-overview.html ). You will use a CmdDeleteStaffObj() command for deleting the key signature and then a CmdInsertStaffObj() command for inserting the new one. But this operation will not do transposition, just replace the accidentals in the key signature and, indirectly, change the pitch of the notes affected by the new accidentals.

2. Perhaps your question is referring to playing transposing instruments, in which the notated pitch is not the sounding pitch. For instance, in an score for a clarinet in B-flat, a written C note should be played as a B-flat. If your question refers to this, the answer is that playback of transposing instruments is not yet implemented in Lomse. The C note in previous example will be played as C pitch and not as B-flat. My first thought on this is that dealing with transposing instruments will only require to add information to the Lomse internal model for encoding that it is a transposing instrument as well as the transposition to apply for playback. As all this information is currently present in MusicXML files it should not be complex to program it and should not take much time.

3. Finally, perhaps you are interested in transposing an score or a fragment, that is, raising or lowering the notated pitch and the key signature (and, therefore, the sounding pitch). This will be a high level edition operation as you will have to replace current key signature and traverse all the score (or the desired measures) for changing the pitch of the affected notes. Implementing this is not complex but you will have to work on the internal model and your code could be affected by future changes in Lomse internals. As this is a frequent edition operation, I think it is better to implement an edition command for this. It is not complex and should not take much time.

Please tell me which of these interpretations fit better with your question, or help me to understand better your needs. In any case, options 2 and 3 should be implemented in Lomse in the long term.

**Comment by juuk100** [comment]
If you access the linked page below, you can upload and play the xml file.
(I ran it on a Chrome browser.)
https://www.soundslice.com/musicxml-viewer/

Please upload the attached Edelweiss.xml file.

[Edelweiss.zip](https://github.com/lenmus/lomse/files/1413051/Edelweiss.zip)

Then click the Settings icon in the bottom right of the score page.
Control the "KEY TRANSPOSITION" item in the setting popup.
You can see that the right score is changed and the playing sound is also changed.

I need it.

**Comment by cecilios** [comment]
Ok. I know have clear view of your needs. What you need is option 3. In any case, as both 2 & 3 are necessary, I'm opening an issue for each one (#92 & # 93), and closing this one. I will give priority to #92
