### ISSUE TITLE
As for the actual size of the score.

### ISSUE THREAD

**Issue by juuk100** [lenmus/lomse#91]
I set the code as below and output the score to the screen.

In initialize_lomse ()
int pixel_format = k_pix_format_rgba32;
int resolution = 150;

The actual pixel size required at 150 dpi is 1240 * 1754.
(Refer to the API documentation.)
I have defined a buffer as shown below to output only one sheet of music.

create_rendering_buffer (1240, 1754);

However, the actual score displayed on the screen is 290 * 410 pixels.
Why are the sizes different?
I expected the score size to be the same as the buffer size.
When I look at the data in the buffer, it is filled with margins (gray) except 290 * 410 pixel size.

**Comment by cecilios** [comment]
Hi juuk100,
I apologize for the delay in commenting on this and on all other issues you opened (#88 & #89); you opened these issues while I was out of the country on a short vacation. I have just returned today and have a lot of work on the table, so along the week I will try to deal with your posts. Sorry!

**Comment by cecilios** [comment]
Please, could you send me your create_rendering_buffer() code?

**Comment by juuk100** [comment]
I hope you have had a good time on vacation.
Do not be sorry. I have no problem at all. :)

Here is my code:
void DrawScore::create_rendering_buffer(int width, int height)
{
    //allocate memory for the Lomse rendering buffer.
    //Any existing buffer is automatically deleted by Lomse.
    
#define BYTES_PER_PIXEL 4   //the chosen format is RGBA, 32 bits
    
    // allocate a new rendering buffer
    delete_rendering_buffer();
    m_nBufWidth = width;
    m_nBufHeight = height;
    m_pdata_len = m_nBufWidth * m_nBufHeight * BYTES_PER_PIXEL;
    m_pdata = (unsigned char*)malloc(m_nBufWidth * m_nBufHeight * BYTES_PER_PIXEL);
    
    //Attach this memory to be used as Lomse rendering buffer
    int stride = m_nBufWidth * BYTES_PER_PIXEL;     //number of bytes per row
    m_rbuf_window.attach(m_pdata, m_nBufWidth, m_nBufHeight, stride);
    
    m_view_needs_redraw = true;
}

And the code to create an image from the buffer is:
cocos2d::Image image;
image.initWithRawData((const unsigned char*)m_pdata, m_pdata_len, m_nBufWidth, m_nBufHeight, sizeof(unsigned char));

So the size of the image is 1240 * 1754 pixels, but the space actually occupied by the score is 290 * 410 pixels.

**Comment by juuk100** [comment]
There was a problem with the display settings on my device.
After modifying cocos2d-x's revolution, I confirmed that it is displayed normally.
I'm sorry to bother you.
