### ISSUE TITLE
Problem with "delete m_pPresenter" in destructor

### ISSUE THREAD

**Issue by juuk100** [lenmus/lomse#96]
After rendering the score to the attached xml file,
Calling "delete m_pPresenter" on my destructor will crash the debugger after printing:

pointer being freed was not allocated

Is it a problem with the xml file?

[101_002.xml.zip](https://github.com/lenmus/lomse/files/1426331/101_002.xml.zip)

**Comment by cecilios** [comment]
The xml file seems to be correct. After some initial investigation it looks like a lomse problem when deleting notes within an slur. Also I have noticed some problems in the rendering of this score so I will have to investigate more.
